version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    groups:
      pip-dependencies:
        patterns:
          - "*"
